//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzytnikRSS.RssService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Source : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RssItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RssItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private System.DateTime pubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime pubDate {
            get {
                return this.pubDateField;
            }
            set {
                if ((this.pubDateField.Equals(value) != true)) {
                    this.pubDateField = value;
                    this.RaisePropertyChanged("pubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odswiez", ReplyAction="*")]
        void Odswiez();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Odswiez", ReplyAction="*")]
        System.Threading.Tasks.Task OdswiezAsync();
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu PobierzLinkiZBazyResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzLinkiZBazy", ReplyAction="*")]
        CzytnikRSS.RssService.PobierzLinkiZBazyResponse PobierzLinkiZBazy(CzytnikRSS.RssService.PobierzLinkiZBazyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzLinkiZBazy", ReplyAction="*")]
        System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzLinkiZBazyResponse> PobierzLinkiZBazyAsync(CzytnikRSS.RssService.PobierzLinkiZBazyRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu link z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzStronyWgLinku", ReplyAction="*")]
        CzytnikRSS.RssService.PobierzStronyWgLinkuResponse PobierzStronyWgLinku(CzytnikRSS.RssService.PobierzStronyWgLinkuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PobierzStronyWgLinku", ReplyAction="*")]
        System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzStronyWgLinkuResponse> PobierzStronyWgLinkuAsync(CzytnikRSS.RssService.PobierzStronyWgLinkuRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzLinkiZBazyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzLinkiZBazy", Namespace="http://tempuri.org/", Order=0)]
        public CzytnikRSS.RssService.PobierzLinkiZBazyRequestBody Body;
        
        public PobierzLinkiZBazyRequest() {
        }
        
        public PobierzLinkiZBazyRequest(CzytnikRSS.RssService.PobierzLinkiZBazyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PobierzLinkiZBazyRequestBody {
        
        public PobierzLinkiZBazyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzLinkiZBazyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzLinkiZBazyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CzytnikRSS.RssService.PobierzLinkiZBazyResponseBody Body;
        
        public PobierzLinkiZBazyResponse() {
        }
        
        public PobierzLinkiZBazyResponse(CzytnikRSS.RssService.PobierzLinkiZBazyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzLinkiZBazyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CzytnikRSS.RssService.Source[] PobierzLinkiZBazyResult;
        
        public PobierzLinkiZBazyResponseBody() {
        }
        
        public PobierzLinkiZBazyResponseBody(CzytnikRSS.RssService.Source[] PobierzLinkiZBazyResult) {
            this.PobierzLinkiZBazyResult = PobierzLinkiZBazyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzStronyWgLinkuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzStronyWgLinku", Namespace="http://tempuri.org/", Order=0)]
        public CzytnikRSS.RssService.PobierzStronyWgLinkuRequestBody Body;
        
        public PobierzStronyWgLinkuRequest() {
        }
        
        public PobierzStronyWgLinkuRequest(CzytnikRSS.RssService.PobierzStronyWgLinkuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzStronyWgLinkuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string link;
        
        public PobierzStronyWgLinkuRequestBody() {
        }
        
        public PobierzStronyWgLinkuRequestBody(string link) {
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzStronyWgLinkuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzStronyWgLinkuResponse", Namespace="http://tempuri.org/", Order=0)]
        public CzytnikRSS.RssService.PobierzStronyWgLinkuResponseBody Body;
        
        public PobierzStronyWgLinkuResponse() {
        }
        
        public PobierzStronyWgLinkuResponse(CzytnikRSS.RssService.PobierzStronyWgLinkuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PobierzStronyWgLinkuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CzytnikRSS.RssService.RssItem[] PobierzStronyWgLinkuResult;
        
        public PobierzStronyWgLinkuResponseBody() {
        }
        
        public PobierzStronyWgLinkuResponseBody(CzytnikRSS.RssService.RssItem[] PobierzStronyWgLinkuResult) {
            this.PobierzStronyWgLinkuResult = PobierzStronyWgLinkuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : CzytnikRSS.RssService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<CzytnikRSS.RssService.WebServiceSoap>, CzytnikRSS.RssService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Odswiez() {
            base.Channel.Odswiez();
        }
        
        public System.Threading.Tasks.Task OdswiezAsync() {
            return base.Channel.OdswiezAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CzytnikRSS.RssService.PobierzLinkiZBazyResponse CzytnikRSS.RssService.WebServiceSoap.PobierzLinkiZBazy(CzytnikRSS.RssService.PobierzLinkiZBazyRequest request) {
            return base.Channel.PobierzLinkiZBazy(request);
        }
        
        public CzytnikRSS.RssService.Source[] PobierzLinkiZBazy() {
            CzytnikRSS.RssService.PobierzLinkiZBazyRequest inValue = new CzytnikRSS.RssService.PobierzLinkiZBazyRequest();
            inValue.Body = new CzytnikRSS.RssService.PobierzLinkiZBazyRequestBody();
            CzytnikRSS.RssService.PobierzLinkiZBazyResponse retVal = ((CzytnikRSS.RssService.WebServiceSoap)(this)).PobierzLinkiZBazy(inValue);
            return retVal.Body.PobierzLinkiZBazyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzLinkiZBazyResponse> CzytnikRSS.RssService.WebServiceSoap.PobierzLinkiZBazyAsync(CzytnikRSS.RssService.PobierzLinkiZBazyRequest request) {
            return base.Channel.PobierzLinkiZBazyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzLinkiZBazyResponse> PobierzLinkiZBazyAsync() {
            CzytnikRSS.RssService.PobierzLinkiZBazyRequest inValue = new CzytnikRSS.RssService.PobierzLinkiZBazyRequest();
            inValue.Body = new CzytnikRSS.RssService.PobierzLinkiZBazyRequestBody();
            return ((CzytnikRSS.RssService.WebServiceSoap)(this)).PobierzLinkiZBazyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CzytnikRSS.RssService.PobierzStronyWgLinkuResponse CzytnikRSS.RssService.WebServiceSoap.PobierzStronyWgLinku(CzytnikRSS.RssService.PobierzStronyWgLinkuRequest request) {
            return base.Channel.PobierzStronyWgLinku(request);
        }
        
        public CzytnikRSS.RssService.RssItem[] PobierzStronyWgLinku(string link) {
            CzytnikRSS.RssService.PobierzStronyWgLinkuRequest inValue = new CzytnikRSS.RssService.PobierzStronyWgLinkuRequest();
            inValue.Body = new CzytnikRSS.RssService.PobierzStronyWgLinkuRequestBody();
            inValue.Body.link = link;
            CzytnikRSS.RssService.PobierzStronyWgLinkuResponse retVal = ((CzytnikRSS.RssService.WebServiceSoap)(this)).PobierzStronyWgLinku(inValue);
            return retVal.Body.PobierzStronyWgLinkuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzStronyWgLinkuResponse> CzytnikRSS.RssService.WebServiceSoap.PobierzStronyWgLinkuAsync(CzytnikRSS.RssService.PobierzStronyWgLinkuRequest request) {
            return base.Channel.PobierzStronyWgLinkuAsync(request);
        }
        
        public System.Threading.Tasks.Task<CzytnikRSS.RssService.PobierzStronyWgLinkuResponse> PobierzStronyWgLinkuAsync(string link) {
            CzytnikRSS.RssService.PobierzStronyWgLinkuRequest inValue = new CzytnikRSS.RssService.PobierzStronyWgLinkuRequest();
            inValue.Body = new CzytnikRSS.RssService.PobierzStronyWgLinkuRequestBody();
            inValue.Body.link = link;
            return ((CzytnikRSS.RssService.WebServiceSoap)(this)).PobierzStronyWgLinkuAsync(inValue);
        }
    }
}
